# 多次元配列の計算

通常のリスト

In [1]:
a = [1,2,3,4]

In [2]:
print(a)

[1, 2, 3, 4]


numpyで配列の作成

In [3]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


配列の次元確認

In [4]:
np.ndim(A)

1

 配列の形状はshapeで求まる。shapeは関数ではなくインスタンス変数

In [5]:
A.shape

(4,)

In [6]:
A.shape[0]

4

2次元配列の作成

In [7]:
B = np.array([[1,2],[3,4],[5,6]])

In [8]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
np.ndim(B)

2

In [10]:
B.shape

(3, 2)

## 行列の内積

2x2の行列を内積

In [11]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [12]:
B = np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [13]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

2x3と3x2の行列を内積

In [14]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [15]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [16]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

2x2と2x3の行列を内積はエラーになる

In [21]:
C = np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [22]:
A.shape

(2, 3)

In [23]:
np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## ニューラルネットワークの内積

In [24]:
X = np.array([1,2])
X.shape

(2,)

In [25]:
W = np.array([[1,3,5],[2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [26]:
W.shape

(2, 3)

In [28]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]


## 3層ニューラルネットワーク

In [31]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [34]:
def identity_function(x):
    return x

In [32]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    return network

In [35]:
def forward(network, x):
    W1, W2, W3 = network['W1'],network['W2'],network['W3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    y = identity_function(a3)
    
    return y
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
print(y) 

[0.31682708 0.69627909]
