# 多次元配列の計算

通常のリスト

In [6]:
a = [1,2,3,4]

In [8]:
print(a)

[1, 2, 3, 4]


numpyで配列の作成

In [1]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


配列の次元確認

In [3]:
np.ndim(A)

1

 配列の形状はshapeで求まる。shapeは関数ではなくインスタンス変数

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

2次元配列の作成

In [11]:
B = np.array([[1,2],[3,4],[5,6]])

In [12]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
np.ndim(B)

2

In [14]:
B.shape

(3, 2)

## 行列の内積

2x2の行列を内積

In [15]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [16]:
B = np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [18]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

2x3と3x2の行列を内積

In [19]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [20]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [21]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

2x2と2x3の行列を内積はエラーになる

In [22]:
C = np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [23]:
A.shape

(2, 3)

In [24]:
np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)