In [1]:
import numpy as np

In [2]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a)

In [4]:
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [5]:
sum_exp_a = np.sum(exp_a)

In [6]:
print(sum_exp_a)

74.1221542101633


In [7]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


## softmax関数

In [9]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a
    return y

In [10]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [11]:
np.sum(y)

1.0

In [12]:
np.sum(y[0])

0.01821127329554753

In [13]:
np.sum(y[1])

0.24519181293507392

In [14]:
np.sum(y[2])

0.7365969137693786